import { handleError } from '../handleError'

test('Error handler function', () => {
  
})

